# Generated by Django 4.1.5 on 2023-03-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_playername_score_player_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='player_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='score',
            name='player_score',
            field=models.IntegerField(),
        ),
    ]
