# Generated by Django 4.1.5 on 2023-06-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_score_player_name_alter_score_player_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_score', models.IntegerField()),
            ],
        ),
    ]
