# Generated by Django 4.1.5 on 2023-06-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_score2_score3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score2',
        ),
        migrations.DeleteModel(
            name='Score3',
        ),
        migrations.AddField(
            model_name='score',
            name='player_score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='player_score3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='player_score',
            field=models.IntegerField(default=0),
        ),
    ]
