# Generated by Django 4.1.5 on 2023-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_score2_delete_score3_score_player_score2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_score2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Score3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_score3', models.IntegerField(default=0)),
            ],
        ),
    ]
