# Generated by Django 4.1.5 on 2023-06-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_score2_score3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='player_score2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='player_score3',
        ),
    ]
